# Generated by Django 5.1.3 on 2024-11-18 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('surname', models.CharField(blank=True, max_length=30)),
                ('role', models.CharField(choices=[('STUDENT', 'student'), ('CAPTAIN', 'captain'), ('PROFESSOR', 'professor'), ('ADMINISTRATOR', 'administrator')], max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_type', models.CharField(blank=True, max_length=20)),
                ('institute', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'unique_together': {('course_name', 'course_type', 'institute')},
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(choices=[('1', '09:00'), ('2', '10:40'), ('3', '12:40'), ('4', '14:20'), ('5', '16:20'), ('6', '18:00')], max_length=1)),
                ('location', models.CharField(choices=[('В-86', 'Проспект Вернадского 86'), ('МП-1', 'Малвя Пироговская 1'), ('СТ-17', 'Стромынкина 17')], max_length=10)),
                ('audience', models.CharField(max_length=10)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
                ('group', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.group')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
            options={
                'unique_together': {('date', 'time', 'audience', 'location')},
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=10, unique=True)),
                ('token_created', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='members', to='base.group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_memberships', to='base.user')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('grade_type', models.CharField(choices=[('ATTENDENCE', 'attendence'), ('ACTIVITIES', 'activities'), ('ACHIEVMENTS', 'achievments'), ('TEST', 'test')], max_length=15)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
            options={
                'unique_together': {('student', 'course')},
            },
        ),
    ]
