# Generated by Django 5.1.3 on 2024-11-14 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='professor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.users'),
        ),
    ]
