# Generated by Django 5.1.3 on 2024-11-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_group_schedule_groups_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='groups',
        ),
        migrations.AddField(
            model_name='schedule',
            name='groups',
            field=models.ManyToManyField(to='base.group'),
        ),
    ]
