# Generated by Django 5.1.3 on 2024-11-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_schedule_groups_schedule_groups'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Н', 'Н'), ('У', 'У'), ('+', '+')], max_length=1)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.user')),
            ],
        ),
    ]
