# Generated by Django 5.1.3 on 2024-11-14 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_schedules_time_remove_users_username_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Courses',
            new_name='Course',
        ),
        migrations.RenameModel(
            old_name='Enrollments',
            new_name='Enrollment',
        ),
        migrations.RenameModel(
            old_name='Grades',
            new_name='Grade',
        ),
        migrations.RenameModel(
            old_name='Groups',
            new_name='Group',
        ),
        migrations.RenameModel(
            old_name='GroupMembers',
            new_name='GroupMember',
        ),
        migrations.RenameModel(
            old_name='Schedules',
            new_name='Schedule',
        ),
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
