# Generated by Django 5.1.3 on 2024-11-14 17:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_course_course_type_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='institute',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='group_id',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.group'),
        ),
    ]
