# Generated by Django 5.1.3 on 2024-11-19 14:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_user_first_enter_user_last_enter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction_code', models.CharField(max_length=10)),
                ('direction_name', models.CharField(max_length=100)),
                ('courses', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='base.course')),
            ],
            options={
                'unique_together': {('direction_code', 'direction_name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='direction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.direction'),
        ),
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together={('student', 'direction')},
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
    ]
