# Generated by Django 5.1.3 on 2024-11-19 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_direction_alter_enrollment_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='courses',
        ),
        migrations.AddField(
            model_name='direction',
            name='courses',
            field=models.ManyToManyField(to='base.course'),
        ),
    ]
