# Generated by Django 5.1.3 on 2024-11-19 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_direction_courses_direction_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='hours',
            field=models.IntegerField(null=True),
        ),
    ]
