# Generated by Django 5.1.3 on 2024-11-14 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_remove_course_course_code_alter_course_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='location',
            field=models.CharField(choices=[('В-86', 'Проспект Вернадского 86'), ('МП-1', 'Малвя Пироговская 1'), ('СТ-17', 'Стромынкина 17')], max_length=10),
        ),
    ]
