# Generated by Django 5.1.3 on 2024-11-25 17:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_course_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='token_created',
        ),
        migrations.AlterField(
            model_name='token',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.user'),
        ),
    ]
