# Generated by Django 5.1.3 on 2024-11-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_schedule_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('ATDNC', 'attendence'), ('ACTVT', 'activities'), ('ACHVMNT', 'achievments'), ('TEST', 'test')], max_length=10),
        ),
    ]
