# Generated by Django 5.1.3 on 2024-11-15 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_grade_grade_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('STUDENT', 'student'), ('CAPTAIN', 'captain'), ('PROFESSOR', 'professor'), ('ADMINISTRATOR', 'administrator')], max_length=15),
        ),
        migrations.AlterField(
            model_name='grade',
            name='grade_type',
            field=models.CharField(blank=True, choices=[('ATTENDENCE', 'attendence'), ('ACTIVITIES', 'activities'), ('ACHIEVMENTS', 'achievments'), ('TEST', 'test')], max_length=15),
        ),
    ]
